apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappkubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webappkubernetes
  template:
    metadata:
      labels:
        app: webappkubernetes
    spec:
      containers:
      - name: webappkubernetes
        image: acrcp2alex.azurecr.io/webappkubernetes:casopractico2
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data
          name: app-volume
        ports:
        - containerPort: 443
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: webapp-pvc
      imagePullSecrets:
        - name: acr-secret
